'use client';

import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { CheckCircle, XCircle, AlertCircle, FileText, MessageSquare, Target } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { useState } from 'react';

interface TestValidationProps {
  naiveDetails?: {
    questions: string[];
    answers: string[];
    contexts: string[][];
    ground_truths: string[];
  };
  semanticDetails?: {
    questions: string[];
    answers: string[];
    contexts: string[][];
    ground_truths: string[];
  };
  testDataset?: Array<{
    question: string;
    ground_truth: string;
  }>;
  naiveMetrics?: Array<{
    faithfulness: number;
    answer_relevancy: number;
    answer_correctness: number;
    context_precision: number;
    context_recall: number;
  }>;
  semanticMetrics?: Array<{
    faithfulness: number;
    answer_relevancy: number;
    answer_correctness: number;
    context_precision: number;
    context_recall: number;
  }>;
}

export function TestValidation({ naiveDetails, semanticDetails, testDataset, naiveMetrics, semanticMetrics }: TestValidationProps) {
  const [expandedItems, setExpandedItems] = useState<Set<number>>(new Set());

  const toggleExpanded = (index: number) => {
    const newExpanded = new Set(expandedItems);
    if (newExpanded.has(index)) {
      newExpanded.delete(index);
    } else {
      newExpanded.add(index);
    }
    setExpandedItems(newExpanded);
  };

  if (!naiveDetails || !semanticDetails || !testDataset) {
    return (
      <Card>
        <CardContent className="p-6 text-center text-muted-foreground">
          <AlertCircle className="h-8 w-8 mx-auto mb-2" />
          <p>No test data available. Run an evaluation to see test questions and answers.</p>
        </CardContent>
      </Card>
    );
  }

  const questions = naiveDetails.questions;

  return (
    <div className="space-y-6">
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <FileText className="h-5 w-5" />
            Test Questions & Validation
          </CardTitle>
          <p className="text-sm text-muted-foreground mt-2">
            Review the questions asked and answers generated by each chunking strategy. 
            This helps validate that the evaluation is testing relevant aspects of your document.
          </p>
        </CardHeader>
        <CardContent>
          <div className="space-y-6">
            {questions.map((question, index) => (
              <div key={index} className="border rounded-lg p-4 space-y-4">
                {/* Question Header */}
                <div className="flex items-start justify-between gap-4">
                  <div className="flex-1">
                    <div className="flex items-center gap-2 mb-2">
                      <MessageSquare className="h-4 w-4 text-primary" />
                      <span className="font-medium text-sm">Question {index + 1}</span>
                    </div>
                    <p className="font-medium">{question}</p>
                  </div>
                  <Button
                    variant="ghost"
                    size="sm"
                    onClick={() => toggleExpanded(index)}
                    className="shrink-0"
                  >
                    {expandedItems.has(index) ? 'Show Less' : 'Show Full Context'}
                  </Button>
                </div>

                {/* Ground Truth */}
                <div className="bg-muted/50 rounded-lg p-3">
                  <div className="flex items-center gap-2 mb-1">
                    <Target className="h-4 w-4 text-green-600" />
                    <span className="text-sm font-medium text-green-600">Expected Answer (Ground Truth)</span>
                  </div>
                  <p className="text-sm">{testDataset[index].ground_truth}</p>
                </div>

                {/* Strategy Comparison */}
                <Tabs defaultValue="comparison" className="w-full">
                  <TabsList className="grid w-full grid-cols-2">
                    <TabsTrigger value="comparison">Answer Comparison</TabsTrigger>
                    <TabsTrigger value="contexts">Retrieved Contexts</TabsTrigger>
                  </TabsList>

                  <TabsContent value="comparison" className="space-y-3 mt-4">
                    {/* Naive Answer */}
                    <div className="border rounded-lg p-3 space-y-2">
                      <div className="flex items-center justify-between">
                        <Badge variant="outline">Naive Chunking</Badge>
                        {naiveMetrics && naiveMetrics[index] && (
                          <div className="flex items-center gap-2">
                            <Badge variant={naiveMetrics[index].answer_correctness > 0.7 ? 'success' : naiveMetrics[index].answer_correctness > 0.4 ? 'default' : 'destructive'}>
                              {(naiveMetrics[index].answer_correctness * 100).toFixed(0)}% Correct
                            </Badge>
                          </div>
                        )}
                      </div>
                      <p className="text-sm">{naiveDetails.answers[index]}</p>
                      {naiveMetrics && naiveMetrics[index] && (
                        <div className="grid grid-cols-2 gap-2 mt-2 text-xs">
                          <div className="flex justify-between">
                            <span className="text-muted-foreground">Faithfulness:</span>
                            <span className="font-mono">{(naiveMetrics[index].faithfulness * 100).toFixed(0)}%</span>
                          </div>
                          <div className="flex justify-between">
                            <span className="text-muted-foreground">Relevancy:</span>
                            <span className="font-mono">{(naiveMetrics[index].answer_relevancy * 100).toFixed(0)}%</span>
                          </div>
                        </div>
                      )}
                    </div>

                    {/* Semantic Answer */}
                    <div className="border rounded-lg p-3 space-y-2">
                      <div className="flex items-center justify-between">
                        <Badge variant="default">Semantic Chunking</Badge>
                        {semanticMetrics && semanticMetrics[index] && (
                          <div className="flex items-center gap-2">
                            <Badge variant={semanticMetrics[index].answer_correctness > 0.7 ? 'success' : semanticMetrics[index].answer_correctness > 0.4 ? 'default' : 'destructive'}>
                              {(semanticMetrics[index].answer_correctness * 100).toFixed(0)}% Correct
                            </Badge>
                          </div>
                        )}
                      </div>
                      <p className="text-sm">{semanticDetails.answers[index]}</p>
                      {semanticMetrics && semanticMetrics[index] && (
                        <div className="grid grid-cols-2 gap-2 mt-2 text-xs">
                          <div className="flex justify-between">
                            <span className="text-muted-foreground">Faithfulness:</span>
                            <span className="font-mono">{(semanticMetrics[index].faithfulness * 100).toFixed(0)}%</span>
                          </div>
                          <div className="flex justify-between">
                            <span className="text-muted-foreground">Relevancy:</span>
                            <span className="font-mono">{(semanticMetrics[index].answer_relevancy * 100).toFixed(0)}%</span>
                          </div>
                        </div>
                      )}
                    </div>
                  </TabsContent>

                  <TabsContent value="contexts" className="space-y-3 mt-4">
                    {/* Naive Contexts */}
                    <div className="space-y-2">
                      <Badge variant="outline">Naive Chunking - Retrieved Contexts</Badge>
                      {naiveDetails.contexts[index] && naiveDetails.contexts[index].length > 0 ? naiveDetails.contexts[index].map((context, ctxIndex) => (
                        <div key={ctxIndex} className="bg-muted/30 rounded p-2">
                          <span className="text-xs text-muted-foreground">Context {ctxIndex + 1}:</span>
                          <p className="text-sm mt-1 whitespace-pre-wrap">
                            {expandedItems.has(index) ? context : (context && context.length > 200 ? context.substring(0, 200) + '...' : context)}
                          </p>
                        </div>
                      )) : (
                        <p className="text-sm text-muted-foreground italic">No contexts retrieved</p>
                      )}
                    </div>

                    {/* Semantic Contexts */}
                    <div className="space-y-2">
                      <Badge variant="default">Semantic Chunking - Retrieved Contexts</Badge>
                      {semanticDetails.contexts[index] && semanticDetails.contexts[index].length > 0 ? semanticDetails.contexts[index].map((context, ctxIndex) => (
                        <div key={ctxIndex} className="bg-muted/30 rounded p-2">
                          <span className="text-xs text-muted-foreground">Context {ctxIndex + 1}:</span>
                          <p className="text-sm mt-1 whitespace-pre-wrap">
                            {expandedItems.has(index) ? context : (context && context.length > 200 ? context.substring(0, 200) + '...' : context)}
                          </p>
                        </div>
                      )) : (
                        <p className="text-sm text-muted-foreground italic">No contexts retrieved</p>
                      )}
                    </div>

                    {!expandedItems.has(index) && (
                      <p className="text-xs text-muted-foreground text-center mt-2">
                        Click "Show Details" to view full contexts
                      </p>
                    )}
                  </TabsContent>
                </Tabs>
              </div>
            ))}
          </div>
        </CardContent>
      </Card>

      {/* Summary Stats */}
      <Card>
        <CardHeader>
          <CardTitle>Test Set Summary</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <div className="text-center">
              <div className="text-2xl font-bold">{questions.length}</div>
              <div className="text-sm text-muted-foreground">Total Questions</div>
            </div>
            <div className="text-center">
              <div className="text-2xl font-bold">
                {naiveMetrics ? 
                  (naiveMetrics.reduce((sum, m) => sum + m.answer_correctness, 0) / naiveMetrics.length * 100).toFixed(0) + '%' 
                  : '-'}
              </div>
              <div className="text-sm text-muted-foreground">Naive Avg Score</div>
            </div>
            <div className="text-center">
              <div className="text-2xl font-bold">
                {semanticMetrics ? 
                  (semanticMetrics.reduce((sum, m) => sum + m.answer_correctness, 0) / semanticMetrics.length * 100).toFixed(0) + '%' 
                  : '-'}
              </div>
              <div className="text-sm text-muted-foreground">Semantic Avg Score</div>
            </div>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}